### ISSUE TITLE
If view size changes, the activity indicator (.gradient) slides left and right continuously

### ISSUE THREAD

**Issue by quantamrhino** [exyte/ActivityIndicatorView#7] opened 2020-08-27 07:06 UTC
I'm running a simple view with an activity indicator int he middle of it, on ipad simulator (ios 14).
In multiwindow mode, when the size of the view changes, the .gradient view keeps rolling back and forth :-)
quite an interesting one.
Aloha
Q

**Comment by f3dm76** [comment] 2020-10-08 05:22
Hey @quantamrhino, I know it's been a while, sorry about that, but I am happy to let you know, the issue is fixed in 0.0.5 version, you are most welcome to check it out. Have a wonderful day!

**Closed as completed by f3dm76** 2020-10-08 05:22 UTC
